odds-command
politicsandwar-community/rift pull request #57
Opened 2023-06-13 07:33 UTC by UnlimitedFrames

2023-06-14 14:29 UTC, mrvillage submitted a review, later dismissed
Great work! Just had a couple small comments/future notes. :)

2023-06-15 03:32 UTC, UnlimitedFrames commented on bot/src/commands/odds.rs
> +    let def_res = Nation::convert(&ctx, defending_nation).await;
shhhhh no commenty yet

2023-06-15 03:33 UTC, UnlimitedFrames commented on bot/src/commands/odds.rs
> +}
there definitally is!!! but shhhhhh give me a min u werent meant to see this

2023-06-15 03:33 UTC, UnlimitedFrames commented on bot/src/commands/odds.rs
> +}
also there kinda is? but its a much more complicated problem than it looks, and doing it like this is easy and fast

2023-06-15 22:13 UTC, mrvillage requested changes

2023-06-15 22:13 UTC, mrvillage commented on bot/src/embeds/pnw.rs
> +                    format!("{}{ }", "https://politicsandwar.com/nation/id=", def.id),
```suggestion
                    format!("https://politicsandwar.com/nation/id={}", def.id),
```

2023-06-15 22:13 UTC, mrvillage commented on bot/src/embeds/pnw.rs
> +                ("Spy Op", "Not Implimented".to_string(), true),
```suggestion
                ("Spy Op", "Not Implemented".to_string(), true),
```

2023-06-15 23:15 UTC, mrvillage approved these changes

2023-06-15 23:15 UTC, merged